[package]
name = "Rustb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
codegen-units = 1
debug=false
lto = "fat"
target-cpu="native"

[dependencies]
ndarray={ version="*", features = ["rayon","blas","matrixmultiply-threading"] }
num-complex="*"
ndarray-linalg={version="*",features=["intel-mkl-static"]}
rayon="*"
gnuplot="*"
jemallocator = "0.3"
jemalloc-sys = "0.3"

[[example]]
name = "WTe2_kp"
path = "examples/WTe2_kp/src/main.rs"
