[package]
name = "Rustb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
codegen-units = 1
debug=false
lto = "fat"

[dependencies]
ndarray={ version="*", features = ["rayon","blas","matrixmultiply-threading"] }
num-complex="*"
ndarray-linalg={version="*",features=["intel-mkl-static"]}
rayon="*"
gnuplot="*"

#[build]
#rustflags = ["-Ctarget-feature=+avx2,+fma"]
