[package]
name = "Rustb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
ndarray={ version="*", features = ["rayon","blas","matrixmultiply-threading"] }
num-complex="*"
ndarray-linalg={version="*",features=["intel-mkl-static"]}
rayon="*"
gnuplot="*"

[[example]]
name="bismuthene"
path="examples/bismuthene.rs"


[build]
rustflags = ["-Ctarget-feature=+avx2,+fma"]
