[build]
rustdocflags = [ "--html-in-header", "./docs-header.html" ]

[alias]
mydoc=["doc","--open","--no-deps"]
testall=["test","--features", "intel-mkl-static","--release"]
runexample=["run","--features", "intel-mkl-static","--example"]
